### ISSUE TITLE
Errors handling #question

### ISSUE THREAD

**Issue by naithar** [michalkalinowski-/KituraRequest#1]
Currently `Request` class stores and handles only `RequestError` error types, but there are other error types including `HTTPParserErrorType` that can be thrown in `process` method. 
Maybe there is some sense in handling them all in some way?

First solution i've come to is make both initializer and response methods (including callbacks) throwable so any error type can be handled by `do ... catch` and result looks like this:

``` swift
do {
  try Request(method: .GET, invalidURL)
    .response { request, response, data in
      ...
    }
    ...
} catch let error as RequestError {
  XCTAssertEqual(error, RequestError.InvalidURL)
} catch {
  XCTFail()
}
```

Other solution i've come to is to switch `RequestError` with `ErrorProtocol`. With this test looks like this:

``` swift
let testRequest = Request(method: .GET, invalidURL)
  .response { request, response, data, error in
    ... 
  }

switch testRequest.error {
  case let error as RequestError:
    XCTAssertEqual(error, RequestError.InvalidURL)
  default:
    XCTFail()
}
```

**Comment by michalkalinowski-** [comment]
how about this:
Request error can have another case storing NSError:

``` swift
enum NetworkingError: ErrorProtocol {
  case InvalidURL
  case NoSchemeProvided
  case NoHostProvided
  case Other(NSError)
  case NotImplemented
}
```

then catch becomes:

``` swift
catch {
      self.request = nil
      if let e = error as! NetworkingError {
        self.error = e
      } else {
        self.error = RequestError.Other(error)
      }
    }
```

this also shows clearly if the error comes from `KituraRequest` module or some other dependencies. What do you think?

**Comment by naithar** [comment]
This could solve many problems, actually this solution looks better than the ones i suggested :) 
The only problem i can see is some specific error handling depending on it's actual error type, because it could turn into switch hell like this:

``` swift
switch error {
case . InvalidURL:
   ...
case .Other(let innerError):
    switch innerError {
    case ...
    }
...
}
```

or

``` swift
switch error {
case . InvalidURL:
   ...
case .Other(let innerError) where error ...:
   ...
}
```

This can be solved with my first suggestion by making `init(...)`, `response(...)` and `CompletionHandler` be able to `throw`, but it's surely just an edge case of error checking, so it can probably be ignored.

**Comment by michalkalinowski-** [comment]
the multiple switch cases is a valid point so I think finally I'll settle on a following solution:

``` swift
class Request {
  ...
  var error: ErrorProtocol?

  typealias ResponseArguments = (request: ClientRequest?, response: ClientResponse?, data: NSData?, error:ErrorProtocol?)

init(...) {
    ...
    catch {
        self.request = nil
        self.error = error // since anything that can be thrown complies to ErrorProtocol
      }

```

Then there is no need to have Other(NSError) in RequestError. Thanks for the input, much appreciatied!

**Comment by naithar** [comment]
No problem, glad the solution was found :)
